version: '3.4'

services:
  catalogdb:
    image: postgres  
    
  basketdb:
    image: postgres 

  hm.catalogapi:
    image: ${DOCKER_REGISTRY-}hmcatalogapi
    build:
      context: ..
      dockerfile: src/Services/hm.CatalogApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


